version: 2
jobs:
  test_webapp:
    working_directory: ~/jenkins-timeline-plugin
    docker:
      - image: maven:3.6.0-jdk-8-alpine
    steps:
      - checkout
      - run: apk add make npm
      - run: make test_webapp

  test:
    working_directory: ~/jenkins-timeline-plugin
    docker:
      - image: maven:3.6.0-jdk-8-alpine
    steps:
      - checkout
      - run: apk add make
      - run: make test_webapp
      - run: make test
          
workflows:
  version: 2
  build_and_test:
      jobs:
          - test_webapp
          - test:
              requires:
                - test_webapp

